[package]
name = "frontend_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rfd = "0.4"
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["json", "blocking", "rustls-tls"] }
serde_json = "1.0"
